export const GOOGLE_REVIEWS = [
  {
    id: 1,
    author: 'farzana fazil',
    rating: 5,
    text: 'An exceptional team that delivers beyond expectations. Their planning, coordination, and on-ground execution were seamless and highly professional. Every detail was handled with precision, making our corporate event smooth, impactful, and stress-free. Truly a reliable partner for any large or small-scale corporate events.',
    date: '2026-03-06',
    source: 'Google',
  },
  {
    id: 2,
    author: 'Sradha Sivadasan',
    rating: 5,
    text: 'Absolutely fantastic experience with Orbinoz Event Planners! From start to finish, their team was professional, creative, and incredibly organized. They brought our vision to life perfectly and made the event stress-free and memorable. Highly recommend their services!',
    date: '2025-07-06',
    source: 'Google',
  },
  {
    id: 3,
    author: 'Arun K raj',
    rating: 4,
    text: 'Excellent service! The event was flawlessly organized, from planning to execution. The team was professional, attentive, and creative, ensuring every detail was perfect. Highly recommended for anyone seeking a hassle-free and memorable experience!',
    date: '2025-07-06',
    source: 'Google',
  },
  {
    id: 4,
    author: 'Krishna Sreeram',
    rating: 5,
    text: "I'm so happy with the work done by Orbinoz Event Planners. They literally saved me in the last minute to organize an event for me. Well done guys, and looking forward for collaborating with you. Anyone in need for event planners without a doubt go for them 🤩",
    date: '2023-07-06',
    source: 'Google',
  },
  {
    id: 5,
    author: 'Mirsana Sherin KP',
    rating: 5,
    text: "The event was beautifully organized, and the team's professionalism and warm hospitality made the entire experience exceptional.",
    date: '2025-07-06',
    source: 'Google',
  },
  {
    id: 6,
    author: 'Rijin K.R',
    rating: 5,
    text: 'Excellent event management team! They helped us plan and execute a flawless event. Highly recommended.',
    date: '2023-07-06',
    source: 'Google',
  },
  {
    id: 7,
    author: 'Ashique ak',
    rating: 5,
    text: 'From start to finish, the coordination was flawless, and every detail was thoughtfully handled.',
    date: '2025-07-06',
    source: 'Google',
  },
  {
    id: 8,
    author: 'Srilakshmi Sathyan',
    rating: 5,
    text: "I'm extremely pleased with the work of Orbinoz Event Planners. Very professional and trustworthy.",
    date: '2023-07-06',
    source: 'Google',
  },
  {
    id: 9,
    author: 'Divya Prasannan',
    rating: 5,
    text: 'The services was pretty good and staffs are also welcoming all the best for the team.',
    date: '2023-07-06',
    source: 'Google',
  },
  {
    id: 10,
    author: 'ZUBIN DHARANI',
    rating: 5,
    text: 'Great Coordination and Superb Management of Activities. Highly Recommended.',
    date: '2023-07-06',
    source: 'Google',
  },
];
